import { config } from "dotenv";
config(); // Load .env for LANGSMITH_API_KEY and other vars

import { ChatPromptTemplate } from "@langchain/core/prompts";
import { push } from "langchain/hub";
import { Client } from "langsmith";

const langsmithApiKey = process.env.LANGSMITH_API_KEY;
if (!langsmithApiKey) {
  throw new Error(
    "Missing LANGSMITH_API_KEY in .env. Set the key for the target tenant before running."
  );
}

// Load the username from env (this might be a tenant ID or username)
const langsmithUsername = process.env.LANGSMITH_USERNAME;
if (!langsmithUsername) {
  throw new Error("Missing LANGSMITH_USERNAME in .env");
}

const promptName = process.env.LANGSMITH_PROMPT_NAME;
if (!promptName) {
  const errMsg = "Missing environment variable: LANGSMITH_PROMPT_NAME";
  throw new Error(errMsg);
}

const promptBaseName = promptName; // Replace if different

// Updated system message with clearer JSON format instructions
const systemMessage = `You are a lead parser. Extract only the following requested fields from the subject and text provided.

Fields to extract:
- customer_name: Name of customer requesting service. Could be first name, last name, full name, etc.
- customer_number: Mobile/phone number of customer requesting service. Should be a valid US number format.
- customer_address: Address of customer requesting service. Can be full address, street name along with zip, etc.
- service_requested: Service requested by customer, such as plumbing, HVAC, electrical, etc.
- provider_lead_id: ID found that may look like a unique ID generated by lead provider for the lead.
- lead_metadata: Other contextual info like requested service/job details, booking date & time, additional details provided by customer, etc. Do NOT include redundant info like customer's contact info or address. Trim to only include new/unique information.

IMPORTANT: You MUST return ONLY valid JSON. Do not include any markdown formatting, code blocks, or explanatory text. Return a JSON object with this exact structure:

{
  "customer_name": "value or null",
  "customer_number": "value or null",
  "customer_address": "value or null",
  "service_requested": "value or null",
  "provider_lead_id": "value or null",
  "lead_metadata": {} or null
}

If any field cannot be found in the input, set it to null. Return ONLY the JSON object, nothing else.`;

// Human template with placeholders (this enables substitution)
const humanMessageTemplate = "subject: {subject}\ntext: {text}";

// Create the templated prompt
const correctedPrompt = ChatPromptTemplate.fromMessages([
  ["system", systemMessage],
  ["human", humanMessageTemplate],
]);

// Run the push using the env var for the path
(async () => {
  try {
    // Try to get the actual username from LangSmith API
    let actualUsername = langsmithUsername;
    const isTenantId = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(langsmithUsername);
    
    if (isTenantId) {
      // If LANGSMITH_USERNAME is a tenant ID, fetch the actual username from API
      try {
        const response = await fetch("https://api.smith.langchain.com/whoami", {
          headers: {
            "Authorization": `Bearer ${langsmithApiKey}`,
            "Content-Type": "application/json",
          },
        });
        
        if (response.ok) {
          const userInfo = await response.json();
          actualUsername = userInfo.username || userInfo.id || langsmithUsername;
          console.log(`Authenticated as: ${actualUsername}`);
        } else {
          console.warn(`Could not fetch user info, using provided username: ${langsmithUsername}`);
        }
      } catch (apiErr) {
        console.warn(`API call failed, using provided username: ${langsmithUsername}`);
      }
    }
    
    // Build the prompt path
    // If LANGSMITH_USERNAME is a tenant ID, we need the actual username
    // The API key format lsv2_pt_ suggests it's a project API key which may have limited permissions
    let fullPromptPath: string;
    
    if (isTenantId) {
      // Try to get organizations/workspaces the API key has access to
      try {
        const orgsResponse = await fetch("https://api.smith.langchain.com/orgs", {
          headers: {
            "Authorization": `Bearer ${langsmithApiKey}`,
            "Content-Type": "application/json",
          },
        });
        
        if (orgsResponse.ok) {
          const orgs = await orgsResponse.json();
          if (orgs && orgs.length > 0) {
            // Use the first organization's username
            actualUsername = orgs[0].username || orgs[0].name || actualUsername;
            console.log(`Found organization: ${actualUsername}`);
          }
        }
      } catch (orgErr) {
        console.warn("Could not fetch organizations");
      }
      
      fullPromptPath = `${actualUsername}/${promptBaseName}`;
    } else {
      fullPromptPath = `${actualUsername}/${promptBaseName}`;
    }
    
    console.log(`Pushing prompt to: ${fullPromptPath}`);
    console.log(`Note: If you get a tenant error, your API key may need tenant-level permissions.`);
    console.log(`Project API keys (lsv2_pt_...) may not have permission to create prompts.`);
    console.log(`Consider using a user API key instead.\n`);
    
    // Use the langchain/hub push function which handles the prompt format correctly
    const commitHash = await push(fullPromptPath, correctedPrompt);
    console.log(`Success! Pushed corrected prompt to "${fullPromptPath}" with commit: ${commitHash}`);
    console.log(`Update your .env LANGSMITH_PROMPT_NAME to "${fullPromptPath}:${commitHash}" or "${fullPromptPath}:latest" if preferred.`);
  } catch (err) {
    const errorMessage = (err as Error).message;
    console.error(`\n❌ Push failed: ${errorMessage}\n`);
    
    if (errorMessage.includes("Cannot create a prompt for another tenant")) {
      console.error("🔑 API Key Issue Detected:");
      console.error("   Your API key appears to be a project API key (lsv2_pt_...)");
      console.error("   Project API keys don't have tenant-level permissions to create prompts.\n");
      console.error("✅ Solution:");
      console.error("   1. Go to https://smith.langchain.com/settings");
      console.error("   2. Generate a USER API key (not a project API key)");
      console.error("   3. Update your .env file with the new LANGSMITH_API_KEY");
      console.error("   4. Make sure LANGSMITH_USERNAME is set to your actual username (not tenant ID)\n");
    }
    
    if ((err as any).stack && process.env.DEBUG === "true") {
      console.error("Stack trace:", (err as any).stack);
    }
    process.exit(1);
  }
})();